/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'background': '#060606',
        'on-background': '#e2e2e2',
        'primary': '#ffffff',
        'on-primary': '#000000',
        'secondary': '#a0acc1',
        'on-secondary': '#000000',
        'surface': '#0c0c0c',
        'on-surface': '#ffffff',
        'surface-variant': '#1a1a1a',
        'on-surface-variant': '#a0a0a0',
        'outline': '#333333',
        'surface-container': '#111111',
        'surface-container-high': '#161616',
        'surface-container-highest': '#1c1c1c',
        'surface-container-low': '#0a0a0a',
        'surface-container-lowest': '#050505',
        'primary-container': '#222222',
        'on-primary-container': '#ffffff',
        'secondary-container': '#1e2530',
        'on-secondary-container': '#ffffff',
        'error': '#ff5449',
        'on-error': '#000000',
        'error-container': '#220000',
        'on-error-container': '#ffdad6',
      },
      fontFamily: {
        'headline': ['Inter', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
